name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Zip published output
      run: |
        cd publish
        zip -r ../app.zip .
        cd ..
    - name: List root directory (debug)
      run: ls -la

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: HelloCloudApi
        environment_name: HelloCloudApi-env
        version_label: app.zip
        region: us-east-1
        deployment_package: app.zip.zip